# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title FORM Algorithm using Rcpp
#' @name form
#' @description Calculates the failure probability and reliability index using the FORM algorithm
#' @param g A function representing the limit state function
#' @param mean A NumericVector of the mean values of the input variables
#' @param sigma A NumericVector of the standard deviations of the input variables
#' @return A List with failure probability \code{pf} and reliability index \code{beta}
#' @examples
#' \dontrun{
#' g <- function(x) { x[1] + x[2] - 3 }
#' mean <- c(2, 2)
#' sigma <- c(1, 1)
#' result <- form(g, mean, sigma)
#' print(result)
#' }
#' @export
form <- function(g, mean, sigma) {
    .Call('_riar_form', PACKAGE = 'riar', g, mean, sigma)
}

